### ISSUE TITLE
How to modify the start point location and the target point location in PointNavigation?

### ISSUE THREAD

**Issue by Sunnyzhr** [facebookresearch/splitnet#10]
In the [Evaluation part](https://github.com/facebookresearch/splitnet#evaluation), I want to change the position of target goal point. How can I do it?
I've tried to modified codes here https://github.com/facebookresearch/splitnet/blob/197ad405c1387bfde16abaf4705b7e0dab628f4f/base_habitat_rl_runner.py#L321, but I doesn't work.
Thanks for your attention!

**Comment by danielgordon10** [comment]
You will have to change it in the dataset itself. See https://github.com/facebookresearch/splitnet/blob/master/dataset_dump/create_pointnav_dataset.py on generating a new dataset.

**Comment by Sunnyzhr** [comment]
Thank you so much!
