### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB(GPU 0; 3.81 GiB total capacity; 2.21 GiB already allocated; 137.56 MiB free; 2.37 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by Sunnyzhr** [facebookresearch/splitnet#11]
Thanks for your attention! I really need your help.
## Problem description
At first it seems normal:
|===============================+======================+======================|
|   0  GeForce GTX 1650    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P0    15W /  N/A |   1364MiB /  3903MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
However, it suddenly runs out of memory after "made dataset".

> ...
> Feeding dummy batch
> Done feeding dummy batch 13.576
> Starting make dataset
> made dataset
> Dataset creation time 127.643
> Feeding dummy batch
> Traceback (most recent call last):
> ...

## What I've tried
1. reboot
2. let `batch_size` be 1
3. `nvidia-smi`, and `sudo kill -9 XXX`
4. `python -c "import torch;torch.cuda.empty_cache()"`
5. `gc.collect()`

## Error message.
> (habitat-env) u@c:~/Desktop/splitnet$  cd /home/u/Desktop/splitnet ; /usr/bin/env /home/u/anaconda3/envs/habitat-env/bin/python /home/u/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher 33059 -- /home/u/Desktop/splitnet/train_splitnet.py --algo supervised --encoder-network-type ShallowVisualEncoder --log-prefix output_files/pointnav/gibson/splitnet_pretrain --eval-interval 2500 --lr 2.5e-4 --value-loss-coef 0.5 --dataset gibson --data-subset train --num-processes 1 --num-forward-rollout-steps 128 --task pointnav --pytorch-gpu-ids 0 --render-gpu-ids 0 --end-to-end 
> Feeding dummy batch
> Done feeding dummy batch 13.576
> Starting make dataset
> made dataset
> Dataset creation time 127.643
> Feeding dummy batch
> Traceback (most recent call last):
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/u/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
>     cli.main()
>   File "/home/u/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
>     run()
>   File "/home/u/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
>     runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/u/Desktop/splitnet/train_splitnet.py", line 578, in <module>
>     main()
>   File "/home/u/Desktop/splitnet/train_splitnet.py", line 573, in main
>     runner = HabitatRLTrainAndEvalRunner()
>   File "/home/u/Desktop/splitnet/train_splitnet.py", line 35, in __init__
>     super(HabitatRLTrainAndEvalRunner, self).__init__(create_decoder)
>   File "/home/u/Desktop/splitnet/eval_splitnet.py", line 60, in __init__
>     super(HabitatRLEvalRunner, self).__init__(create_decoder)
>   File "/home/u/Desktop/splitnet/base_habitat_rl_runner.py", line 74, in __init__
>     self.setup(create_decoder)
>   File "/home/u/Desktop/splitnet/train_splitnet.py", line 79, in setup
>     self.optimizer.update(self.rollouts, self.shell_args)
>   File "/home/u/Desktop/splitnet/networks/optimizers.py", line 362, in update
>     pt_util.remove_dim(rollouts.obs[:-1], 1), shell_args.use_visual_loss
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/site-packages/dg_util/python_utils/pytorch_util.py", line 384, in forward
>     return getattr(self, self.scope_list[0])(*input, **kwargs)
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/u/Desktop/splitnet/networks/networks.py", line 97, in forward
>     x = block(x)
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/u/Desktop/splitnet/networks/building_blocks.py", line 131, in forward
>     x = self.upsample(up_x)
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/u/Desktop/splitnet/networks/building_blocks.py", line 57, in forward
>     x, size=self.size, scale_factor=self.scale_factor, mode=self.mode, align_corners=self.align_corners
>   File "/home/u/anaconda3/envs/habitat-env/lib/python3.6/site-packages/torch/nn/functional.py", line 3151, in interpolate
>     return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
> RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 3.81 GiB total capacity; 2.21 GiB already allocated; 137.56 MiB free; 2.37 GiB reserved in total by PyTorch)

**Comment by danielgordon10** [comment]
Habitat uses the GPU for rendering and PyTorch uses the GPU for deep learning. It's possible that your GPU memory isn't large enough to do both.

**Comment by Sunnyzhr** [comment]
Thanks for help!
