### ISSUE TITLE
Dataset download not working

### ISSUE THREAD

**Issue by imankgoyal** [facebookresearch/splitnet#3]
Thanks for the code. I tried downloading but it seems like the link is not active:
```
 wget https://dl.fbaipublicfiles.com/splitnet/splitnet_dataset.tar.gz
--2019-06-10 18:08:13--  https://dl.fbaipublicfiles.com/splitnet/splitnet_dataset.tar.gz
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.20.22.166, 104.20.6.166, 2606:4700:10::6814:16a6, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.20.22.166|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-06-10 18:08:14 ERROR 403: Forbidden.
```
Also, can you please share the code for generating the `exploration` and `flee` tasks? I could find the code for `point-nav` but not the others. Pardon me if I missed the other ones. Thanks!

**Comment by danielgordon10** [comment]
Thanks for pointing that out. We change the link to tar instead of tar.gz
Try this
`wget https://dl.fbaipublicfiles.com/splitnet/splitnet_dataset.tar`
I will update the instructions as well.

As for exploration/flee datasets, I will see what I can do.

**Comment by danielgordon10** [comment]
So the thing about exploration/flee is they only need a start point, but having a "goal point" doesn't really affect them. So we used the same datasets from pointnav for exploration/flee but we only use the start point component, ignoring the goal. The agent will still be initialized in a proper location, but there is no real need to generate a separate dataset for these tasks.
