### ISSUE TITLE
Failed to clone Habitat-Sim and Habitat-api

### ISSUE THREAD

**Issue by phongnhhn92** [facebookresearch/splitnet#4]
Hello,
I have tried to clone and install Habitat-Sim and Habitat-api within conda environment using this command as suggested from the instructions:
`pip install git+https://github.com/facebookresearch/habitat-sim.git@a674c5c13683a117c06820c54f5bec9c1775800d `
However, it return a lot of errors which seems to be related to pip "Permission denied" within conda environment. 
![image](https://user-images.githubusercontent.com/11288381/59792573-218fa300-92dd-11e9-8c22-53a51163baa1.png)
I wonder how to fix this ? I believe I should not use sudo because if I do so then I will install habitat-sim into the system pip, not the one in the conda environment.

**Comment by abhiskk** [comment]
Please folow the instructions in habitat-sim repository to install. You have to do a `python setup.py install`, also if you still face the access denied issue try using the `--user` flag.

**Comment by phongnhhn92** [comment]
Hi, I tried again today with this command still the same error:
python3 setup.py install --headless --user
I think the problem is this error :
Failed to create temporary file for /home/phong/.ccache/tmp/tmp.cpp_stderr: Permission denied
which means I dont have access in the conda environment.

**Comment by phongnhhn92** [comment]
Update:
I am still not to be able to install habitat-sim on the conda environment but somehow I found a hack way to install it on my global system by changing a few things in the build.sh and cmake dependencies.

**Comment by danielgordon10** [comment]
I'm going to close this issue and recommend that you open it on the main habitat-sim page https://github.com/facebookresearch/habitat-sim/issues

**Comment by danielgordon10** [comment]
Looks like you already did that :) https://github.com/facebookresearch/habitat-sim/issues/83
