### ISSUE TITLE
ACTION_SPACE_TO_SIM_ACTION[ACTION_SPACE[prev_action.squeeze()]] IndexError: list index out of range

### ISSUE THREAD

**Issue by JordanYeomans** [facebookresearch/splitnet#5]
Hi all!

This a really cool project, thank you for sharing!

I had a problem when trying to add the --record-video flag to the eval_splitnet.py. It seems to run 1 episode before an issue pops with draw_obs["action_taken_name"]

To fix, I can simply comment out the line

`draw_obs["action_taken_name"] = SIM_ACTION_TO_NAME[ACTION_SPACE_TO_SIM_ACTION[ACTION_SPACE[prev_action.squeeze()]]]`

and replace with

`draw_obs["action_taken_name"] = ''
`
------
Traceback (most recent call last):
  File "eval_splitnet.py", line 552, in <module>
    main()
  File "eval_splitnet.py", line 548, in main
    runner.evaluate_model()
  File "eval_splitnet.py", line 239, in evaluate_model
    ACTION_SPACE_TO_SIM_ACTION[ACTION_SPACE[prev_action.squeeze()]]
IndexError: list index out of range

**Comment by danielgordon10** [comment]
Good catch. The habitat-api has been updating and changing how action space is dealt with, so sometimes a misalignment between which habitat-api version and splitnet can cause issues like this. I will fix this issue, but there may be others of the same type.
https://github.com/facebookresearch/splitnet/commit/18cac6a006cc88c870f50e5707b63204db6ae820
