### ISSUE TITLE
confusion about habitat-api and habitat-sim version 

### ISSUE THREAD

**Issue by StOnEGiggity** [facebookresearch/splitnet#7]
Hi, 

I found we can't reproduce the experimental results after updating habitat-sim and habitat-api. I know it may be unrelated to this repo. But I am confused about the reason. 
I hope that I can get some advice from you. It's useless even though I check their commit log.

Thanks

**Comment by Danmou** [comment]
I don't know if this is the cause, but the latest version of Habitat [changed the default config](https://github.com/facebookresearch/habitat-api/pull/216) so the episode order is now shuffled by default (which makes more sense, but might give different results). You can try with the old behavior by adding this to the config:
```yaml
ENVIRONMENT:
  ITERATOR_OPTIONS:
    SHUFFLE: False
```

**Comment by StOnEGiggity** [comment]
Sorry for replying late.  I also find the pre-trained models perform worse after I use new habit-api and habitat-sim.  One issue in habitat-api told that it happened because of different order of action space.  However, this method includes three actions.  I believe there is no influence for this repo.  I will check again.  Thanks a lot.

**Comment by StOnEGiggity** [comment]
The problem is related to https://github.com/facebookresearch/habitat-api/issues/148. Following the instruction, I change the config with `POINTGOAL_WITH_GPS_COMPASS_SENSOR `. The results look good. 

I will close this issue. Thanks.

**Comment by phongnhhn92** [comment]
@StOnEGiggity 
Hi, I am on the master branch of habitat-sim and habitat-api, how can i find the config file to apply above changes ?
