### ISSUE TITLE
Training Details?

### ISSUE THREAD

**Issue by BryanBo-Cao** [facebookresearch/splitnet#8]
I love this work and thanks for sharing the code!

I am doing a project and trying to reproduce the result, but I am lost in the code as the start point to train the visual coder. It would be great if you may provide more details of the procedure of training.

Also, an agent would need to collect experience in the habitat environment, it would be great to know the specific procedures. Are they simply stored in a replay buffer with each containing a sequence of [state_{t}, action_{t}, reward{t}, state_{t+1}, action_{t+1}, reward{t+1},...]?

And surely for publication we will cite this paper.

**Comment by danielgordon10** [comment]
You can get started training the visual encoder with [https://github.com/facebookresearch/splitnet/blob/master/supervised_learning/train_splitnet_supervised.sh](url)

We do our RL training using PPO which is an on policy method, so there is no experience replay buffer.
