### ISSUE TITLE
Error on eval_splitnet.sh

### ISSUE THREAD

**Issue by phongnhhn92** [facebookresearch/splitnet#9]
Hi,
Thanks for the code!
I have downloaded the pretrained weights but when I try to execute the eval script I recieved this error:
```
Traceback (most recent call last):
  File "eval_splitnet.py", line 20, in <module>
    from dg_util.python_utils import drawing
ModuleNotFoundError: No module named 'dg_util'
```

**Comment by danielgordon10** [comment]
`pip install git+https://github.com/danielgordon10/dg_util.git`
